site_name: "Pugsley Wiki"
site_url: https://www.surlypugsley.org/
repo_name: "rpvnwnkl/SurlyPugsley"
edit_uri: ""      # disable the default "Edit on GitHub" link if you like

theme:
  name: null             # use a completely custom theme directory
  custom_dir: theme      # ← this tells MkDocs to look under /theme/
  static_templates:
    - 404.html           # if you had a custom 404

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.magiclink
  - pymdownx.tasklist

nav:
  - Home: index.md
  - Original design: pugsley/overview.md
  - Sources & archive:
      - Overview: archive/index.md
      - Dave Gray interview: archive/interview_with_dave_gray_from_surly_bikes/article.md
      - Surly frame-page conversion: frame/pugsley_frame_archived.md
  - About: about.md
