site_name: "Surly Pugsley Wiki"
site_url: https://www.surlypugsley.org/
repo_name: "rpvnwnkl/SurlyPugsley"
edit_uri: ""      # disable the default "Edit on GitHub" link if you like

theme:
  name: null             # use a completely custom theme directory
  custom_dir: theme      # ← this tells MkDocs to look under /theme/
  static_templates:
    - 404.html           # if you had a custom 404

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.magiclink
  - pymdownx.tasklist

nav:
  - Home: index.md
  - About: about.md

  - Pugsley:
      - Overview: pugsley/overview.md
      - History:   pugsley/history.md
      - Quirks:    pugsley/quirks.md
      - Buying Guide: pugsley/buying-guide.md

  - Frame:
      - Frame & Fork & Headset: frame/index.md
      - Geometry:                frame/geometry.md
      - Forks:                   frame/fork.md
      - Headsets:                frame/headset.md

  - Wheels:
      - Overview: wheels/index.md
      - Rims:      wheels/rims.md
      - Hubs:      wheels/hubs.md
      - Tires:     wheels/tires.md

  - Drivetrain:
      - Overview:    drivetrain/index.md
      - Geared:      drivetrain/geared.md
      - Singlespeed: drivetrain/singlespeed.md
      - Fixed Gear:  drivetrain/fixedgear.md
      - IGH:         drivetrain/igh.md
      - Electric:    drivetrain/electric.md

  - Usage & Maintenance:
      - Overview:         usage/index.md
      - Maintenance:      usage/maintenance.md
      - Upgrades:         usage/upgrades.md
      - Packing & Racks:  usage/packing.md
      - Cold Weather Use: usage/cold-weather.md

  - References:
      - FAQ:     references/faq.md
      - Manuals: references/manuals.md
      - Links:   references/links.md
